mod 'puppetlabs-apache', '5.6.0'
mod 'puppetlabs-mysql', '10.7.1'
mod 'puppet-php', '7.1.0'
mod 'puppetlabs-vcsrepo', '3.1.1'
mod 'mediawiki', '1.35.0'
  :git => 'https://github.com/wikimedia/mediawiki.git'
